### Importing required libraries

In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import pandas as pd
import numpy as np
from numpy import array
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Bidirectional

In [3]:
# univariate data preparation
from numpy import array

In [4]:
# split a univariate sequence into samples
def split_sequence(sequence, n_steps):
    X, y = list(), list()
    for i in range(len(sequence)):
    # find the end of this pattern
        end_ix = i + n_steps
        # check if we are beyond the sequence
        if end_ix > len(sequence)-1:
            break
        # gather input and output parts of the pattern
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
        X.append(seq_x)
        y.append(seq_y)
    return array(X), array(y)

In [5]:
raw_seq = [110,125,133,146,158,172,187,196,210]

In [6]:
# choose a number of time steps
n_steps = 3

In [7]:
# split into samples
X, y = split_sequence(raw_seq, n_steps)

In [8]:
# summarize the data
for i in range(len(X)):
    print(X[i], y[i])

[110 125 133] 146
[125 133 146] 158
[133 146 158] 172
[146 158 172] 187
[158 172 187] 196
[172 187 196] 210


In [9]:
# reshape from [samples, timesteps] into [samples, timesteps, features]
n_features = 1

In [12]:
X = X.reshape((X.shape[0], X.shape[1], n_features))
X

array([[[110],
        [125],
        [133]],

       [[125],
        [133],
        [146]],

       [[133],
        [146],
        [158]],

       [[146],
        [158],
        [172]],

       [[158],
        [172],
        [187]],

       [[172],
        [187],
        [196]]])

In [13]:
model = Sequential()

In [14]:
model.add(Bidirectional(LSTM(50, activation='relu'),input_shape = (n_steps,n_features)))

In [15]:
model.add(Dense(1))

In [16]:
model.compile(optimizer='adam',loss='mse')

In [17]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 bidirectional (Bidirectiona  (None, 100)              20800     
 l)                                                              
                                                                 
 dense (Dense)               (None, 1)                 101       
                                                                 
Total params: 20,901
Trainable params: 20,901
Non-trainable params: 0
_________________________________________________________________


In [18]:
# fit model
model.fit(X, y, epochs=200, verbose=0)

In [19]:
#prediction
x_input = array([110,125,133])
x_input = x_input.reshape((1,n_steps, n_features))
yhat = model.predict(x_input, verbose=0)
print(yhat)

[[146.36972]]


In [20]:
#printing next 10 values
for i in range(10):
    x_input = np.array(raw_seq[-3:])
    x_input = x_input.reshape((1,n_steps, n_features))
    yhat = model.predict(x_input, verbose=0)
    w=int(yhat)
    raw_seq.append(w)
    print(w)

223
236
250
264
279
295
311
328
346
365
